version: "3"
services:
  ########################### Database ############################
  db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dell"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 10s
    restart: unless-stopped
    environment:
      - POSTGRES_DB=dell
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data


  ########################### API ##################################
  api:
    image: consultmagesh/fastapi-template:1.7
    restart: unless-stopped
    #build:
    #context: .
    #dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
    volumes:
      - ./logs:/app/logs
      - #./backups:/app/backups
      - #./uploads:/app/uploads
    env_file:
      - .env
############################ UI ##################################

volumes:
  pgdata:
